:stats: {
        :scan_rate: {
                      :pair: [:scan_rate],
                      :units: "",
                      :color: ["#cc0000"],
                      :pname: "Scans/s"
                  },

        :cell_read_rate: { :pair: [:cell_read_rate],
                       :units: "" ,
                       :color: ["#edd400"],
                       :pname: "Cells Read/s"},

        :byte_read_rate: { :pair: [:byte_read_rate],
                       :units: "bytes" ,
                       :color: ["#edd400"],
                       :pname: "Table Bytes Read/s"},

        :disk_read_rate: { :pair: [:disk_read_rate],
                       :units: "bytes" ,
                       :color: ["#edd400"],
                       :pname: "Disk Bytes Read/s"},

	:update_rate: {
                      :pair: [:update_rate],
		      :units: "",
                      :color: ["#c17d11"],
                      :pname: "Updates/s"
                      },

        :cell_write_rate: {
                       :pair: [:cell_write_rate],
                       :units: "" ,
                       :color: ["#73d216"],
                       :pname: "Cells Written/s"
                      },

        :byte_write_rate: {
                       :pair: [:byte_write_rate],
                       :units: "bytes" ,
                       :color: ["#73d216"],
                       :pname: "Table Bytes Written/s"
                      },

        :block_index_memory: {
                       :pair: [ :block_index_memory],
                       :units: "Bytes",
                       :color: ["#5c3566"],
                       :pname: "Block Index Memory"
                       },

        :bloom_filter_memory: {
                       :pair: [:bloom_filter_memory],
                       :units: "Bytes",
                       :color: ["#73d216"],
                       :pname: "Bloom Filter Memory"
                       },

        :bloom_filter_access: {
                       :pair: [:bloom_filter_access],
                       :units: "",
                       :color: ["#ad7fa8"],
                       :pname: "Bloom Filter Accesses"
                       },

        :bloom_filter_maybes: {
                       :pair:  [:bloom_filter_maybes],
                       :units: "",
                       :color: ["#73d216"],
                       :pname: "Bloom Filter Maybes"
                       },

        :disk_used: {
                       :pair: [:disk_used],
                       :units: "Bytes",
                       :color: ["#fcaf3e"],
                       :pname: "Disk Used"
                       },

        :memory_used: {
                      :pair: [:memory_used],
                      :units: "Bytes",
                      :color: ["#c17d11"],
                      :pname: "Memory Used"
                      },
		      
        :memory_allocated: {
                     :pair: [:memory_allocated],
                     :units: "Bytes",
                     :immutable: true,
                     :color: ["#888a85"],
                     :pname: "Memory Allocated"
                     },

        :range_count: { :pair: [:range_count],
                       :units: "" ,
                       :color: ["#73d216"],
                       :pname: "Range Count"}

}
